### ISSUE TITLE
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.

### ISSUE THREAD

**Issue by anwarbolat** [kuzyk/gulp-rigger#15]
TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at C:\Users\*\alinabolat.com\node_modules\gulp-rigger\index.js:20:29
    at Rigger.<anonymous> (C:\Users\*\alinabolat.com\node_modules\rigger\index.js:719:9)
    at emitOne (events.js:96:13)
    at Rigger.emit (events.js:188:7)
    at C:\Users\*\alinabolat.com\node_modules\rigger\index.js:252:16
    at C:\Users\*\alinabolat.com\node_modules\rigger\node_modules\async\lib\async.js:232:13
    at C:\Users\*\alinabolat.com\node_modules\rigger\node_modules\async\lib\async.js:113:21

I am getting this error which I don't understand. Please, could you help me with this error. Please see below the link to my code:
[https://github.com/anuar-bolatov/alinabolat.com.git](https://github.com/anuar-bolatov/alinabolat.com.git)

Kindest regards,
Anuar

**Comment by ndgo** [comment]
You dont have **navigation.html** in partials **directory**, add it and check

**Comment by anwarbolat** [comment]
Great! That was so obvious :) Thank's a lot

**Comment by yasell** [comment]
and I have the same problem in this repo:
https://github.com/tOke3i/biketours

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at Function.Buffer.from (buffer.js:183:11)
    at new Buffer (buffer.js:158:17)
    at /Users/roma/projects/biketours/node_modules/gulp-rigger/index.js:20:29
    at Rigger.<anonymous> (/Users/roma/projects/biketours/node_modules/rigger/index.js:719:9)
    at emitOne (events.js:116:13)
    at Rigger.emit (events.js:211:7)
    at /Users/roma/projects/biketours/node_modules/rigger/index.js:252:16
    at /Users/roma/projects/biketours/node_modules/rigger/node_modules/async/lib/async.js:232:13
    at /Users/roma/projects/biketours/node_modules/rigger/node_modules/async/lib/async.js:113:21
    at /Users/roma/projects/biketours/node_modules/rigger/node_modules/async/lib/async.js:24:16

Can anybody help me ? Thnx

**Comment by Nagibaba** [comment]
Also another issue may always be extra spaces after `.html  `. Try to trim filename and remove extra spaces after file extension. `//= template/head.html    ` ->  `//= template/head.html`

**Comment by Gatvik** [comment]
The name of the directory where my project was located contained parentheses. I removed them and everything worked.
