### ISSUE TITLE
TypeError: must start with number, buffer, array or string

### ISSUE THREAD

**Issue by maroon775** [kuzyk/gulp-rigger#7]
main.js undefined
buffer.js:68
    throw new TypeError('must start with number, buffer, array or string');
          ^
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:68:11)
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\index.js:23:29
    at Rigger.<anonymous> (D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\index.js:719:9)
    at Rigger.emit (events.js:107:17)
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\index.js:252:16
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\node_modules\async\lib\async.js:232:13
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\node_modules\async\lib\async.js:113:21
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\node_modules\async\lib\async.js:24:16
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\node_modules\async\lib\async.js:229:17
    at D:\SERVER_U2\frontend\esterfurs\node_modules\gulp-rigger\node_modules\rigger\index.js:391:21

**Comment by falur** [comment]
Sorry for my English.

The error occurs when you include a recursive file. 
Ie when one investment is invested another file.
How to solve problemmu found.

**Comment by falur** [comment]
Проблема происходит когда в файл который сам инклудится, пытаешься еще заинклудит другой файл. Я так понял он не поддерживает рекурсивную вставку

**Comment by Priler** [comment]
I still facing this issue, but only with my .js files.
I think it's because of js comment system.

**Comment by cyberkatze** [comment]
@falur ti yveren 4to vse faili v shablonax pravilno napisani?

had same bug today. Problem was if i start rigger and have in folder files with other names as in my index.html file where i wrote template file with older name.

also be sure that u have all files and all template-urls

Hope this help u! :)

**Comment by falur** [comment]
@cyberkatze Yes, the names and paths are exactly correct, problem is with recursive insertion

**Comment by Vitegor** [comment]
Sorry for my English.

I had the same problem. I had files main.js and top_nav.js. In main.js file I included top_nav.js file like showed below:

//=top_nav.js

The problem was that I not writen space after '='

**Comment by sinneren** [comment]
@falur Не просто рекурсивную, а вообще множественную. 2 файла подряд - уже упал

**Comment by m11z** [comment]
I have the same error. If I want include html file to html file that OLREADY include on the page.html (for example). Rigger crash.
@falur Тоже, что и у Вас.

**Comment by Postnov** [comment]
Также проблема появляется когда в конце строки подключения файла есть пробелы.
Also the problem appears when the end of the connection string of the file contains spaces.

Has anyone found a way to handle such errors?
